[book]
authors = ["adamsky"]
multilingual = false
src = "src"
title = "The Outcome Project Book"

[output.html]
theme = "src/theme"
default-theme = "coal"
mdbook-theme = "coal"
cname = "book.theoutcomeproject.com"

[build]
build-dir = "docs"
create-missing = false
